### ISSUE TITLE
Minor: Point and geom matching outputs fields in different order

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/sharedstreets-js#26]
Most of the output fields for point matches and geom matches are the same, but they're written out in a very different order. Can we make a small change to make this consistent?

**Comment by morganherlocker** [comment]
@emilyeros Do you mean the order of the JSON properties? This is generally not deterministic, and determined by the JavaScript engine. In the case of an array, we should sort.

**Comment by emilyeros** [comment]
@morganherlocker Yes, that's what I mean. And if that's the case, then I think we can close this issue.
