### ISSUE TITLE
Clear cache or write over it when there's been an error or version update

### ISSUE THREAD

**Issue by emilyeros** [sharedstreets/sharedstreets-js#46]
(We've been doing this manually for testing the CLI)

We ran into this problem when trying to get the mobility connector up and running - we hit a timeout on creating tiles/graph, and then any future tests would use the cached files and get an error message. Would be great to clear this out automatically when necessary, otherwise we will need to troubleshoot this 1:1 with cities.

**Comment by kpwebb** [comment]
Cache now announces if the graph is incomplete and provides instructions to delete the directory.
