### ISSUE TITLE
Adding TravisCI automated Testing (Need approval by admin)

### ISSUE THREAD

**Issue by DenisCarriere** [sharedstreets/sharedstreets-js#8]
@kpwebb Would be nice to set up TravisCI to have some automated testing at each build.

Just waiting for you to approve the GitHub request. (I'm not admin so I can't do it, ** could you add me as admin to `sharedstreets` org?)

![image](https://user-images.githubusercontent.com/550895/35584761-f4a000e4-05c3-11e8-9cae-af7bd4918402.png)

Travis is free to use, it's awesome.

travis-ci.org

The config to set it up are minimal, example with TurfJS

https://github.com/Turfjs/turf/blob/master/.travis.yml

**.travis.yml**

```yml
language: node_js
cache: yarn
node_js:
  - node
```

**Comment by kpwebb** [comment]
yes! Adding now. Also want to set up something that integrates testing of the java and JS modules to help catch things like the ID errors. That's going to be a bit tricky (integrate JS test module into Java tests), but totally worth doing... adding a ticket now.

**Comment by kpwebb** [comment]
Done!

**Comment by kpwebb** [comment]
Also adding you to admin!

**Comment by DenisCarriere** [comment]
👍 Nice! TravisCI is setup for both `sharedstreets` & `sharedstreets-pbf`, I'll include a little badge in their READMEs
