### ISSUE TITLE
 Error: 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/osrm/v5.22.0/Release/node-v83-linux-x64.tar.gz

### ISSUE THREAD

**Issue by Aamer09** [sharedstreets/sharedstreets-js#95]

**Comment by russbiggs** [comment]
It looks like you are using Node v14.17.6. OSRM which is a dependency for sharedstreets-js only works on Node v11.

**Comment by Aamer09** [comment]
@russbiggs works good thanks . What about this error ? 

should i clone the repo and make changes accordingly ? i dont get this


![Screenshot from 2021-09-07 19-36-30](https://user-images.githubusercontent.com/36763789/132358895-4d9eab2a-f0d9-4e3c-ae73-89b496b20714.png)

**Comment by russbiggs** [comment]
i believe that has to do with this issue mentioned in https://github.com/sharedstreets/sharedstreets-js/issues/92 it seems like that user in that user solved it by doing a null check

**Comment by Aamer09** [comment]
@russbiggs  

I have made changes as suggested by that user .I pulled his file on my Local

![Screenshot from 2021-09-07 20-20-59](https://user-images.githubusercontent.com/36763789/132365678-60699ad3-c982-4e35-a693-164bf8c5982b.png)

This the null check above .. I think the three errors we see are TypeScript Errors...
